
<div class="a11yAccordeon akkordeon" id="accordeon2" role="tablist" multiselectable="true">	
	<ul class="level-1">
		<!--Parent #1-->
		<li class="akkordeon-inner" aria-controls="level-2" role="tab">
			<div class="topic"><h3>Radbörse</h3></div>
			<ul class="level-2" aria-labelledby="topic" role="akkordeon">
				<li><div class="description">Sie findet jährlich im Frühjahr im Radhaus Kastner in Kuppenheim statt. Als Tauschbörse rund ums Rad ist sie inzwischen ein fester Bestandteil unserer Aktivitäten in Kuppenheim. Sie wird von der Bevölkerung gerne genutzt, um gut gerüstet und sattelfest die ersten warmen Sonnenstrahlen während eines Radausflugs zu genießen.</div>
				<article>
					<header>
						<time datetime="2013">2013</time>
						<h4><a href="#">Auch die 23. Radbörse war ein Riesenerfolg - rund 17.000 Besucher</a></h4>
					</header>
					<p>Die Radbörse der terre des hommes Arbeitsgruppe Murgtal/Mittelbaden, die mittlerweile zu einer der größten Radbörsen im mittelbadischen Raum gehört, lockte am vergangenen Samstag rund 17.000 Besucher nach Kuppenheim. In weniger als drei Stunden wechselten dabei 231 gebrauchte Fahrräder (55%) ihre Besitzer. <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time datetime="2012">2012</time>
						<h4><a href="#">2500 Euro Erlös bei der 22. Kuppenheimer Fahrradbörse</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2011">2011</time>
						<h4><a href="#">2000 Euro Erlös bei der 21. Kuppenheimer Fahrradbörse</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2010">2010</time>
						<h4><a href="#">1900 Euro Erlös bei der 20. Kuppenheimer Fahrradbörse</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2009">2009</time>
						<h4><a href="#">1900 Euro Erlös bei der 19. Kuppenheimer Fahrradbörse</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2008">2008</time>
						<h4><a href="#">Fahrradbörse brachte 1600 Euro Erlös</a></h4>
					</header>
				</article>
				</li>
			</ul>	
		</li>
		<!--Parent #2-->
		<li class="akkordeon-inner" aria-controls="level-2" role="tab">
			<div class="topic"><h3>Konzerte</h3></div>
			<ul class="level-2" aria-labelledby="topic" role="akkordeon">
				<li><div class="description">Unentdeckt, unerforscht, unergründlich: Schicksal des provisorischen Substituts zwischen nutzloser Platzhalterei und dem nie formulierten Anspruch auf Beachtung. Ein Schattendasein auf der unbekann...</div>
				<article>
					<header>
						<time datetime="2013">2013</time>
						<h4><a href="#">Ja, wir finden auch, dass man über die Copy noch mal reden sollte. Das hier kann es jedenfalls ni...</a></h4>
					</header>
					<p>Ein Holzschuhmacher und ein Bogenschütze mit Brot- beziehungsweise Wassersack durchschritten eine Saccharose-Pfütze. Zwar war sie gottlos, aber zäh wie Lack. Der Schütze sprach: "Wir müssen sie ent... <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time datetime="2012">2012</time>
						<h4><a href="#">Freilebende Gummibärchen gibt es nicht. Dieser Kauf...</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2011">2011</time>
						<h4><a href="#">Hunger. Stufe für Stufe schob sie sich die Treppe hinauf. Pizza Funghi Salami, Sternchen "Salami" gleich Blockwurst.</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2010">2010</time>
						<h4><a href="#">Streng dem definierten Wesen des Blindtextes folgend, fungiere ich als solcher und gebe mich unve...</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2009">2009</time>
						<h4><a href="#">Mit seiner Aufnahme in die Elite war Knechts Leben auf eine andre Ebene verpflanzt, es war der er..</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2008">2008</time>
						<h4><a href="#">Dies ist ein Blindtext. Blindtexte sind zumeist weder informativ noch interessant, sondern ausges...</a></h4>
					</header>
				</article>
				</li>
			</ul>	
		</li>
		<!--Parent #3-->
		<li class="akkordeon-inner" aria-controls="level-2" role="tab">
			<div class="topic"><h3>Kinderfest</h3></div>
			<ul class="level-2" aria-labelledby="topic" role="akkordeon">
				<li><div class="description">Als eines Tages im Internet neben allen Highway-Junkies auch alle Chinesen vernetzt waren, kam Pab Li Shing aus Win Link Shou auf die Idee, dem Chaos ein Ende zu bereiten und für immer steinreich z...</div>
				<article>
					<header>
						<time datetime="2013">2013</time>
						<h4><a href="#">Lieber Kunde und Leser, falls Sie keine Probleme haben, diesen Blindtext schnell und zügig zu les..</a></h4>
					</header>
					<p>Dieser text hat eigentlich gar keinen wirklichen inhalt. aber er hat auch keine relevanz, und deswegen ist das egal. er dient lediglich als platzhalter. um mal zu zeigen, wie diese stelle der seite... <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time datetime="2012">2012</time>
						<h4><a href="#">Lieber Onkel Reinhard, schon lange wollte ich Dir sagen, dass ich Dich für einen ganz tollen Text..</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2011">2011</time>
						<h4><a href="#">Wie beiläufig, beim Umblättern der Buchseiten, habe ich Dein B berührt. Man hatte Dich mir als Ty...</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2010">2010</time>
						<h4><a href="#">Bevor Sie diesen Text lesen, sollten Sie unbedingt zwei Dinge tun. Erstens sollten Sie der Agentu...</a></h4>
					</header>
				</article>	
				<article>
					<header>
						<time datetime="2009">2009</time>
						<h4><a href="#">Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und Konsonantien leben die Blindtext...</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2008">2008</time>
						<h4><a href="#">Ich bin nur ein kleiner Blindtext. Wenn ich gross bin, will ich Ulysses von James Joyce werden. A...</a></h4>
					</header>
				</article>
				</li>
			</ul>	
		</li>
		<!--Parent #4-->
		<li class="akkordeon-inner" aria-controls="level-2" role="tab">
			<div class="topic"><h3>Basar</h3></div>
			<ul class="level-2" aria-labelledby="topic" role="akkordeon">
				<li><div class="description">Schön, dass Sie neugierig reinschauen, obwohl hier ja eigentlich noch gar kein richtiger Text steht, sondern nur der sogenannte Blindtext. Der aber soll Ihnen diesmal mehr Spass machen als das "Eir...</div>
				<article>
					<header>
						<time datetime="2013">2013</time>
						<h4><a href="#">In Deutschland gibt es rund 120.000 Vermögensmillionäre. Sie gelten als die Reichen im Lande. Dam...</a></h4>
					</header>
					<p>Nein, meine Texte les ich nicht, so nicht, stöhnte Oxmox. Er war mit Franklin, Rockwell und dem halbtaxgrauen Panther Weidemann in Memphis (Heartbreak Hotel) zugange. Sie warteten auf die fette Gil... <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time datetime="2012">2012</time>
						<h4><a href="#">Um mich herum ein Feuerwerk vermeintlicher Wichtigkeiten. Darwinistisches Design drängt mich in d...</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2011">2011</time>
						<h4><a href="#">Dies ist ein Blindtext. Bitte beachten Sie den weiteren Inhalt dieses Textes nicht. Es handelt si...</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2010">2010</time>
						<h4><a href="#">Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und Konsonantien leben die Blindtext...</a></h4>
					</header>
				</article>	
				<article>
					<header>
						<time datetime="2009">2009</time>
						<h4><a href="#">Ich bin eine Copy für Anzeigen und ich erkläre den Superwitz aus Headline und Bild da oben. Meist...</a></h4>
					</header>
				</article>
				<article>
					<header>
						<time datetime="2008">2008</time>
						<h4><a href="#">Seit zwei Jahren ist meine Arbeit in Düsseldorf. Meine Familie lebt dagegen in Hamburg. Und dazwi...</a></h4>
					</header>
				</article>
				</li>
			</ul>	
		</li>
	</ul>
</div>