<div id="pattern" class="pattern">	
	<nav id="menu" class="menu" role="akkordeon">
		<ul class="level-1">
			  <!--Parent #1-->
			  <li class="has-subnav">
				    <a href="#">Radbörse</a>
				    <ul class="level-2">
    					<li><div class='description'>Sie findet jährlich im Frühjahr im Radhaus Kastner in Kuppenheim statt. Als Tauschbörse rund ums Rad ist sie inzwischen ein fester Bestandteil unserer Aktivitäten in Kuppenheim. Sie wird von der Bevölkerung gerne genutzt, um gut gerüstet und sattelfest die ersten warmen Sonnenstrahlen während eines Radausflugs zu genießen.</div>
						<article>
							<header>
								<time>2013</time>
								<a href="#">Überschrift</a>
							</header>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos culpa suscipit inventore fuga fugit sed perspiciatis omnis laborum nostrum rerum rem distinctio expedita ratione animi reprehenderit laboriosam voluptatem temporibus maiores! <a href="#">mehr...</a></p>
						</article>
						<article>
							<header>
								<time>2012</time>
								<a href="#">Überschrift</a>
							</header>
						</article>
						<article>
							<header>
								<time>2011</time>
								<a href="#">Überschrift</a>
							</header>
						</article>
						<article>
							<header>
								<time>2010</time>
								<a href="#">Überschrift</a>
							</header>
						</article>
						</li>
					</ul>	
				</li>
				<!--Parent #2-->
				<li class="has-subnav">
					<a href="#">Konzerte</a>
						<ul class="level-2">
							<li><div class='description'>description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores sunt quod inventore non nulla in culpa impedit aut soluta. Ipsam suscipit quibusdam nostrum perferendis obcaecati cum quisquam illum similique sequi.</div>
							<article>
								<header>
									<time>2013</time>
									<a href="#">Überschrift</a>
								</header>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos culpa suscipit inventore fuga fugit sed perspiciatis omnis laborum nostrum rerum rem distinctio expedita ratione animi reprehenderit laboriosam voluptatem temporibus maiores! <a href="#">mehr...</a></p>
							</article>
							<article>
								<header>
									<time>2012</time>
									<a href="#">Überschrift</a>
								</header>
							</article>
							<article>
								<header>
									<time>2011</time>
									<a href="#">Überschrift</a>
								</header>
							</article>
							<article>
								<header>
									<time>2010</time>
									<a href="#">Überschrift</a>
								</header>
							</article>	
							</li>
						</ul>	
					</li>
				<!--Parent #3-->
				<li class="has-subnav">
					<a href="#">Kinderbasar</a>
						<ul class="level-2">
							<li><div class='description'>description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores sunt quod inventore non nulla in culpa impedit aut soluta. Ipsam suscipit quibusdam nostrum perferendis obcaecati cum quisquam illum similique sequi.</div>
							<article>
								<header>
									<time>2013</time>
									<a href="#">Überschrift</a>
								</header>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos culpa suscipit inventore fuga fugit sed perspiciatis omnis laborum nostrum rerum rem distinctio expedita ratione animi reprehenderit laboriosam voluptatem temporibus maiores! <a href="#">mehr...</a></p>
							</article>
							<article>
								<header>
									<time>2012</time>
									<a href="#">Überschrift</a>
								</header>
							</article>
							<article>
								<header>
									<time>2011</time>
									<a href="#">Überschrift</a>
								</header>
							</article>
							<article>
								<header>
									<time>2010</time>
									<a href="#">Überschrift</a>
								</header>
							</article>	
							</li>
						</ul>	
					</li>
				<!--Parent #4-->
				<li class="has-subnav">
					<a href="#">Konzerte</a>
						<ul class="level-2">
							<li><div class='description'>description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores sunt quod inventore non nulla in culpa impedit aut soluta. Ipsam suscipit quibusdam nostrum perferendis obcaecati cum quisquam illum similique sequi.</div>
							<article>
								<header>
									<time>2013</time>
									<a href="#">Überschrift</a>
								</header>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos culpa suscipit inventore fuga fugit sed perspiciatis omnis laborum nostrum rerum rem distinctio expedita ratione animi reprehenderit laboriosam voluptatem temporibus maiores! <a href="#">mehr...</a></p>
							</article>
							<article>
								<header>
									<time>2012</time>
									<a href="#">Überschrift</a>
								</header>
							</article>
							<article>
								<header>
									<time>2011</time>
									<a href="#">Überschrift</a>
								</header>
							</article>
							<article>
								<header>
									<time>2010</time>
									<a href="#">Überschrift</a>
								</header>
							</article>	
							</li>
						</ul>	
				</li>
		</ul>
	</nav>
</div>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/akkordeon.js"></script>