<div class="akkordeon" id="akkordeon" role="akkordeon">	
	<ul class="level-1">
		<!--Parent #1-->
		<li class="has-subnav">
			<div class='topic'>Radbörse</div>
			<ul class="level-2">
				<li><div class='description'>Sie findet jährlich im Frühjahr im Radhaus Kastner in Kuppenheim statt. Als Tauschbörse rund ums Rad ist sie inzwischen ein fester Bestandteil unserer Aktivitäten in Kuppenheim. Sie wird von der Bevölkerung gerne genutzt, um gut gerüstet und sattelfest die ersten warmen Sonnenstrahlen während eines Radausflugs zu genießen.</div>
				<article>
					<header>
						<time>2013</time>
						<a href="#">Auch die 23. Radbörse war ein Riesenerfolg - rund 17.000 Besucher</a>
					</header>
					<p>Die Radbörse der terre des hommes Arbeitsgruppe Murgtal/Mittelbaden, die mittlerweile zu einer der größten Radbörsen im mittelbadischen Raum gehört, lockte am vergangenen Samstag rund 17.000 Besucher nach Kuppenheim. In weniger als drei Stunden wehselten dabei 231 gebrauchte Fahrräder (55%) ihre Besitzer. <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time>2012</time>
						<a href="#">2500 Euro Erlös bei der 22. Kuppenheimer Fahrradbörse</a>
					</header>
				</article>
				<article>
					<header>
						<time>2011</time>
						<a href="#">2000 Euro Erlös bei der 21. Kuppenheimer Fahrradbörse</a>
					</header>
				</article>
				<article>
					<header>
						<time>2010</time>
						<a href="#">1900 Euro Erlös bei der 20. Kuppenheimer Fahrradbörse</a>
					</header>
				</article>
				<article>
					<header>
						<time>2009</time>
						<a href="#">1900 Euro Erlös bei der 19. Kuppenheimer Fahrradbörse</a>
					</header>
				</article>
				<article>
					<header>
						<time>2008</time>
						<a href="#">Fahrradbörse brachte 1600 Euro Erlös</a>
					</header>
				</article>
				</li>
			</ul>	
		</li>
		<!--Parent #2-->
		<li class="has-subnav">
			<div class='topic'>Konzerte</div>
			<ul class="level-2">
				<li><div class='description'>description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores sunt quod inventore non nulla in culpa impedit aut soluta. Ipsam suscipit quibusdam nostrum perferendis obcaecati cum quisquam illum similique sequi.</div>
				<article>
					<header>
						<time>2013</time>
						<a href="#">Überschrift</a>
					</header>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos culpa suscipit inventore fuga fugit sed perspiciatis omnis laborum nostrum rerum rem distinctio expedita ratione animi reprehenderit laboriosam voluptatem temporibus maiores! <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time>2012</time>
						<a href="#">Überschrift</a>
					</header>
				</article>
				<article>
					<header>
						<time>2011</time>
						<a href="#">Überschrift</a>
					</header>
				</article>
				<article>
					<header>
						<time>2010</time>
						<a href="#">Überschrift</a>
					</header>
				</article>	
				</li>
			</ul>	
		</li>
		<!--Parent #3-->
		<li class="has-subnav">
			<div class='topic'>Kinderfest</div>
			<ul class="level-2">
				<li><div class='description'>description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores sunt quod inventore non nulla in culpa impedit aut soluta. Ipsam suscipit quibusdam nostrum perferendis obcaecati cum quisquam illum similique sequi.</div>
				<article>
					<header>
						<time>2013</time>
						<a href="#">Überschrift</a>
					</header>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos culpa suscipit inventore fuga fugit sed perspiciatis omnis laborum nostrum rerum rem distinctio expedita ratione animi reprehenderit laboriosam voluptatem temporibus maiores! <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time>2012</time>
						<a href="#">Überschrift</a>
					</header>
				</article>
				<article>
					<header>
						<time>2011</time>
						<a href="#">Überschrift</a>
					</header>
				</article>
				<article>
					<header>
						<time>2010</time>
						<a href="#">Überschrift</a>
					</header>
				</article>	
				</li>
			</ul>	
		</li>
		<!--Parent #4-->
		<li class="has-subnav">
			<div class='topic'>Basar</div>
			<ul class="level-2">
				<li><div class='description'>description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores sunt quod inventore non nulla in culpa impedit aut soluta. Ipsam suscipit quibusdam nostrum perferendis obcaecati cum quisquam illum similique sequi.</div>
				<article>
					<header>
						<time>2013</time>
						<a href="#">Überschrift</a>
					</header>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos culpa suscipit inventore fuga fugit sed perspiciatis omnis laborum nostrum rerum rem distinctio expedita ratione animi reprehenderit laboriosam voluptatem temporibus maiores! <a href="#">mehr...</a></p>
				</article>
				<article>
					<header>
						<time>2012</time>
						<a href="#">Überschrift</a>
					</header>
				</article>
				<article>
					<header>
						<time>2011</time>
						<a href="#">Überschrift</a>
					</header>
				</article>
				<article>
					<header>
						<time>2010</time>
						<a href="#">Überschrift</a>
					</header>
				</article>	
				</li>
			</ul>	
		</li>
	</ul>
</div>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/akkordeon.js"></script>