<h2>Archiv für November 2013</h2>
<ul class="archive-list">
    <li>
        <article>
            <h3>Spenden-Aktion für die Menschen auf den Philippinen </h3>
            <time datetime="2013-11-20">Mittwoch, 20. November 2013</time>
            <p>Die Arbeitsgruppe aus Mittelbaden gehört zu den agilsten des Kinderhilfswerks Terre des Hommes im gesamten Bundesgebiet. Vor acht Jahren hatten die AG-Mitglieder mit zahlreichen Partnern und Firmen nach der damaligen Flutkatastrophe in Südostasien mehrere 10 000 Euro an Spenden in den Krisengebieten einsetzen können. Auch nach dem Erdbeben auf Haiti vor drei Jahren war das Engagement groß.</p>
            <a href="#" class="goon">zum Artikel</a>            
        </article>
    </li>
    <li>
        <article>
            <h3>Taifun auf den Philippinen <br>Medizinische Versorgung und Suppenküchen für Kinder</h3>
            <time datetime="2013-11-14">Donnerstag, 14. November 2013</time>
            <p>Alberto Cacayan, Koordinator der terre des hommes-Programme in Südostasien, plant am Freitagmorgen gegen 3:00 Uhr in der vom Taifun Haiyan schwer verwüsteten Stadt Tacloban einzutreffen. Zuvor hat er in Manila Gespräche mit philippinischen Partnerorganisationen geführt, die selbst Hilfsgüter für die Betroffenen organisieren. Diese Hilfspakete sollen über Cebu, die Nachbarinsel der zerstörten Inseln Samar und Leyte, zu den Betroffenen gebracht werden. terre des hommes plant eine Zusammenarbeit mit der Medical Action Group (MAG), einem langjährigen terre des hommes-Partner, der auf Samar gute Kontakte hat und ein Netzwerk von rund 250 Ärzten, Gesundheitsfachkräften, Krankenschwestern und Psychologen mobilisieren kann. Am heutigen Donnerstag werden sich Ärzte der MAG in Samar einen Überblick über den dringendsten Bedarf an medizinischer Hilfe verschaffen und ab Freitag mit der medizinischen Versorgung der ersten 500 Familien, rund 2.500 Menschen, beginnen.</p>
            <a href="#" class="goon">zum Artikel</a>            
        </article>
    </li>
    <li>
        <article>
            <h3>Taifun auf den Philippinen <br>terre des hommes-Partnerorganisationen in Südostasien mobilisieren Hilfe für die Taifun-Opfer</h3>
            <time datetime="2013-11-12">Dienstag, 12. November 2013</time>
            <p>Südostasiatische Partnerorganisationen des internationalen Kinderhilfswerks terre des hommes bereiten erste Hilfen für die Opfer des Taifuns »Haiyan« vor und sammeln teilweise selbst Spenden für die Betroffenen. Dies berichtet Alberto Cacayan, terre des hommes-Büroleiter für Südostasien, der auf dem Weg in die Katastrophenregion ist. »Die Not ist riesengroß, doch es ist ermutigend zu sehen, dass es eine weltweite Hilfsbereitschaft gibt und auch unter unseren Partnern in Südostasien große Solidarität mit den Philippinen herrscht«, so Cacayan.</p>
            <a href="#" class="goon">zum Artikel</a>            
        </article>
    </li>
</ul>