<h2>Schnullerbacke on the road</h2>
<div class="ym-grid">
    <div class="ym-g66 ym-gl">
        <article class="expandable">
            <?php
                include "inc/modules/platzhalterbild3.inc";
                include "inc/modules/blindtext3.inc";
				include "inc/modules/blindtext4.inc";
				include "inc/modules/blindtext2.inc";
                include "inc/modules/blindtext.inc";
            ?>
           
        </article>
    </div>
    <div class="ym-g33 ym-gr">
        <?php
            include 'inc/modules/contentwidget1.inc';
            include 'inc/modules/sponsorendank.inc';
        ?>
    </div>
</div>