<h2>Schnullerbacke on the road</h2>
<div class="ym-grid">
    <div class="ym-g66 ym-gl">
        <article>
            <?php
                include "inc/modules/platzhalterbild3.inc";
                include "inc/modules/blindtext3.inc";
            ?>
            <a href="#">weiterlesen</a>
        </article>
    </div>
    <div class="ym-g33 ym-gr">
        <?php
            include 'inc/modules/contentwidget1.inc';
            include 'inc/modules/sponsorendank.inc';
        ?>
    </div>
</div>