<div class="ym-grid contentwidget-2col">
  <h3>Unsere Spendenkonten</h3>
  <div class="ym-g50 ym-gl contentwidget-g50">
    <div class="contentwidget-left">
      <ul class="nolist">
        <li class="bank">Sparkasse</li>
        <li class="bankname">Baden-Baden Gaggenau</li>
        <li class="iban"> 
          <span>IBAN</span>
          <span>DE40662500300000120790</span>
        </li>
        <li class="bic">     
          <span>BIC</span>
          <span>SOLADES1BAD</span>
        </li>
      </ul>
    </div>
  </div>
  
  <div class="ym-g50 ym-gr  contentwidget-g50">
    <div class="contentwidget-right">
      <ul class="nolist">
        <li class="bank">Volksbank</li>
        <li class="bankname">Osnabr&uuml;ck</li>
        <li class="iban">     
          <span>IBAN</span>
          <span>DE20265900250700800700</span>
        </li>
        <li class="bic">     
          <span>BIC</span>
          <span>GENODEF1OSV</span>
        </li>
      </ul>
    </div> 
  </div>
</div>