<div class="ym-grid contentwidget-2col">
  <h3>Unsere Spendenkonten</h3>
  <div class="ym-g50 ym-gl contentwidget-g50">

    <div class="contentwidget-left">
      <h4>Sparkasse</h4>
      <caption>Baden-Baden-Gaggenau</caption>
      <table>
        <tr>
          <th>IBAN </th>
          <td>DE40662500300000120790</td>
        </tr>
        <tr>
          <th>BIC</th>
          <td>SOLADES1BAD</td> 
        </tr>
      </table>
    </div>
  </div>
  <div class="ym-g50 ym-gr  contentwidget-g50">
    <div class="contentwidget-right">
      <h4>Volksbank</h4>
      <caption>Osnabr&uuml;ck</caption>
      <table>
        <tr>
          <th>IBAN </th>
          <td>DE20265900250700800700</td>
        </tr>
        <tr>
          <th>BIC</th>
          <td>GENODEF1OSV</td>
        </tr>
      </table>
    </div> 
  </div>
</div>