
<div class="ym-grid contentwidget-bg">
  <h3>Das Team</h3>
  <div class="ym-g40 ym-gl contentwidget-left">
    <div class="">
		<img class="flexible" src="images/team-beispielbild.jpg"  alt="Team Bild" >
	</div>
  </div>
  <div class="ym-g60 ym-gr contentwidget-right">
    <div class=""></div>
    <p>Schreiben Sie uns eine 
		<a  href="#">Email</a>
		oder rufen Sie einen
		<a  href="#">Mitarbeiter</a>
		an, wir informieren Sie gerne persönlich.
	</p>
    <a  href="#">
      Hier finden Sie eine Liste all unsere aktiven Mitarbeiter.
    </a>
  </div>
</div>
