<div class="ym-grid contentwidget-2col">
  <h3>Unsere Spendenkonten</h3>
  <div class="ym-g50 ym-gl contentwidget-g50">

    <div class="contentwidget-left">
      <h4>Sparkasse</h4>
      <h5>Baden-Baden Gaggenau</h5>
      <div>
        <span>IBAN</span>
        <span>DE40662500300000120790</span>
      </div>
      <div>
        <span>BIC</span>
        <span>SOLADES1BAD</span>
      </div>
    </div>
  </div>
  <div class="ym-g50 ym-gr  contentwidget-g50">
    <div class="contentwidget-right">
      <h4>Volksbank</h4>
      <h5>Osnabr&uuml;ck</h5>
      <div>
        <span>IBAN</span>
        <span>DE20265900250700800700</span>
      </div>
      <div>
        <span>BIC</span>
        <span>GENODEF1OSV</span>
      </div>
    </div> 
  </div>
</div>