<!--  siehe meine Kommentare in contentwidget1.inc -->
<div class="contentpadded">
	<section>
	<header>
	<small>Vorgestellt</small>
	<h3>Franz Bürk - "Der Feuermacher"</h3>
	</header>
	<article>
	<img src="images/fackelmann.jpg" class="flexible"/>
	<p>Franz Bürk aus Achern - "der Feuermacher" -
	war eine große Bereicherung für das Kinderfest 2001,
	indem er Jung und Alt eindrucksvoll demonstrierte, wie man ohne
	technische Hilfsmittel Feuer entzünden kann.
	</p>
	<a href="#" class="dottedlink" >Mehr in den Meldungen</a>
	</article>
	</section>
</div>