<div class="ym-grid contentwidget-2col-button">
  <h2>Erdbeben in Haiti</h2>
  <div class="ym-g60 ym-gl contentwidget-g50">
    
    <div class="contentwidget-left">
        <p>Hier finden Sie alle wichtigen Meldungen zu dem verheerenden Erdbeben 
		in Haiti Bitte unterstützen Sie uns weiterhin mit Spenden. Ihre Spende - Stichwort: 
		"Erdbeben Haiti". Alle Spenden reichen wir weiter an die Partnerorganisation tdh Lausanne, 
		die vor Ort Hilfe leistet.</p>
		
		<div class="cta cta-button">
	<a class=" ym-clearfix" href="#">
		<img src="images/spenden-icon.gif" alt="" />
		sicher &amp; schnell
	<span>Online spenden bei terre des hommes Deutschland</span>
	</a>
</div>
   </div>
   
  </div>
  <div class="ym-g40 ym-gr  contentwidget-g50">
    <div class="contentwidget-right">
        <ul>
            <li><strong>Spendenkonto</strong></li>
			<li>Sparkasse Baden-Baden / Gaggenau</li>
			<li>IBAN: DE40662500300000120790</li>
            <li>BIC: SOLADES1BAD</li>
        </ul>
        <ul>
            <li><strong>Spendenkonto</strong></li>
            <li>VoBa Baden-Baden / Rastatt</li>
			<li>IBAN: DE64662900000010274800</li>
            <li>BIC: VBRADE6KXXX</li>
        </ul>
    </div> 
  </div>
</div>