
<div class="contentpadded">
    <!--  Wenn, dann müsste das ganze Modul eine Section sein.
          Allerdings ist die Bedingung, dass das Modul so auch auf einer anderen
          Seite platziert sein könnte, es also inhaltlich abgeschlossen ist.
          Das ist hier nicht der Fall. -->
	<!-- <section> -->
	    <!-- JG: Das Bild wird per IMG eingebunden, also gehört es NICHT 
	            in den CSS-Unterordner, sondern in den Haupt-Bilderordner.
	            Die Slashes gingen in die falsche Richtung. 
	            Es fehlt ein Alt-Attribut. -->
	<img src="images/topbild.jpg" alt="Super tolles Inhaltsbild mit toll bedeutungsschwangerem Alternativtext" class="flexible">
	<header>	
	    <small>Der Erlös geht an</small>
	    <h3>Staubige Kindheit</h3>
	</header>
    
    <!--  Nur für den Link ist das hier ziemlich overdone. -->
	<article> 
	    <!-- Links sind generell rot und müssen nicht extra in ein DIV gepackt werden. -->
	    <!-- Den Punkt schreiben Sie am Besten mit der display-Eigenschaft: http://codepen.io/jensgro/pen/bgcqu -->
	    <div class="link">&bull; <a href="#">mehr darüber bei terre des hommes Deutschland</a></div>
	</article>
	<!-- </section> -->
</div>