<div class="contentwidget">
	<header>
	<small>Vorgestellt</small>
	<h3>Franz Bürk - "Der Feuermacher"</h3>
	</header>
	<img src="images/fackelmann.jpg" alt="Mann macht Feuer" class="flexible"/>
	<p>Franz Bürk aus Achern - "der Feuermacher" -
	war eine große Bereicherung für das Kinderfest 2001,
	indem er Jung und Alt eindrucksvoll demonstrierte, wie man ohne
	technische Hilfsmittel Feuer entzünden kann.
	</p>
	<a href="#" class="dottedlink" >Mehr in den Meldungen</a>
</div>