
<div class="contentpadded">
	<small>Vorgestellt</small>
	<h3>Franz Bürk - "Der Feuermacher"</h3>
	<img src=".\css\tdh\images\fackelmann.jpg" />
	<p>Franz Bürk aus Achern - "der Feuermacher" -
	war eine große Bereicherung für das Kinderfest 2001,
	indem er Jung und Alt eindrucksvoll demonstrierte, wie man ohne
	technische Hilfsmittel Feuer entzünden kann.
	</p>
	<a href="#">&bull; Mehr in den Meldungen</a>
</div>