<div class="event">
	<div class="ym-grid">
	<div class="ym-g50 ym-gl">
	<table class="cleantable" >
		<tr><th>Wann</th><td>26.06.2011, ab 18:30</td></tr>
		<tr><th>Wo</th><td>Reithalle Rastatt<br>
							Am Schlossplatz 9<br>
							76437 Rastatt<br>
							<a href="#">Anfahrt</a></td></tr>
	</table>
	</div>
	
	<div class="ym-g50 ym-gr">
	<img src="images/printer.gif" alt="printer icon"/> <a href="#">drucken</a>
	</div>
	</div>
	
</div>