<h3>Grafiken und Fotos</h3>

	<p>Alle eingesetzten Grafiken und Fotos stammen von <a href="http://www.tdh.de/" target="_blank">terre 
		des hommes Deutschland e.V.</a> bzw. sind von terre des hommes 
		Murgtal / Mittelbaden selbst erstellt worden.</p>
	<p><a href="http://www.fotocommunity.de/pc/pc.php4?mypics=1513"><img src="http://www.tdh-murgtal.de/images/depping/motiv8.jpg" class="float-left flexible" alt="Beispielbild aus der Fotocommunity"></a>Urheber 
		der Illustrationen oben links auf jeder Seite ist <a href="http://www.andreasdepping.de/" target="_blank">Andreas 
		Depping</a>, bei dem wir uns herzlich für die Verwendung 
		bedanken. Die Aufnahmen sind in Äthopien entstanden. Andreas 
		war in den Jahren 1988 bis 1991 in Äthiopien als Entwicklungshelfer 
		des DED tätig. Mit seiner Frau und seinen beiden Kindern 
		lebte er in Ambo (ca 130 km westlich von Addis Abeba). Die meisten 
		Porträts sind dort entstanden. Dabei legte er immer großen 
		Wert darauf, dass die Menschen, die er fotografieren wollte genauso 
		viel Freude dabei hatten wie er am fotografieren.</p>
	<p>Weitere schöne Aufnahmen von Andreas Depping findet man in 
		der <a href="http://www.fotocommunity.de/pc/pc.php4?mypics=1513" target="_blank">fotocommunity</a>, 
		von der auch die für unsere Seite verwendeten Fotos stammen.</p>
	<p>Aus designtechnischen Gründen wurden die Originalaufnahmen 
		verkleinert und farblich angepasst. </p>
