<!-- Modul: Navigation -->

<div class="navigation">
<nav role='navigation' class="ym-hlist">
	<!--Liste als Navigation, enthält pro Navigationselement einen Link mit anschliessender Liste
		des entsprechenden Untermenüs. Das Untermenü enthält eine Liste der entsprechenden Links.
	-->
  <ul>
    <li><a href="#">Start</a>
    </li>
    <li><a href="#">Veranstaltungen</a>
    </li>
    <li><a class="active" href="#">Über Uns</a> 			<!-- Die Klasse 'active' markiert den aktuell gewählten Menüpunkt -->
       <div class="submenu"> 								<!-- Bisher nur ein Untermenü -->
        <ul>
          <li><a href="#">Das Team</a></li>
          <li><a href="#">Mitwirkende und Helfer</a></li>
          <li><a class="active" href="#">Sponsoren</a></li>
          <li><a href="#">Über terre de hommes</a></li>
          <li><a href="#">Unsere Aktivitäten</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Meldungen</a>
    </li>
    <li><a href="#">Shop</a>
    </li>
    <li><a href="#">Helfen</a>
    </li>
    <li><a href="#">Presse</a>
    </li>
    <li><a href="#">Kontakt</a>
    </li>
  </ul>
</nav>  
</div> 