<div class="sponsors">
<span>Eine Auswahl unserer langjährigen Sponsoren. Die vollständige Liste der Sponsoren finden <a href="#">Sie hier</a></span>

<ul >
<li><a href="#"><img class="flexible" src="images/sponsors/sponsor1.png" alt="Sponsor 1 Logo"></a></li>
<li><a href="#"><img class="flexible" src="images/sponsors/sponsor2.png" alt="Sponsor 2 Logo"></a></li>
<li><a href="#"><img src="images/sponsors/sponsor3.png" alt="Sponsor 3 Logo"></a></li>
<li><a href="#"><img src="images/sponsors/sponsor4.png" alt="Sponsor 4 Logo"></a></li>
<li><a href="#"><img src="images/sponsors/sponsor5.png" alt="Sponsor 5 Logo"></a></li>
</ul>

</div>
