<!--TODO: Muss später entfert werden-->
<!-- <link rel="stylesheet" type="text/css" href="../../css/tdh/tabelle-1.css"/>  -->

<table name="sponsoren-tab-1" class="sponsoren-tab-1">
	<caption>
			<h3>Sponsorenliste</h3>
		</caption>
<thead>
	<tr>
		<th>Firmenlogo</th>
		<th>Name</th>
		<th>Ort</th>
	</tr>
</thead>
<tbody>
	<tr>
		<td>
			<div>
				<img class="sponsor-img-small" alt="Katze" src="images/einzelnachhilfe.gif"/>
				<img class="sponsor-img-big" alt="Katze" src="images/einzelnachhilfe.gif"/>
			</div>
		</td>
		<td><a href="#">Abacus Nachhilfeinstitut</a></td>
		<td>Gernsbach-Scheuern</td>
	</tr>
	<tr>
		<td></td>
		<td><a href="#">ABAKUS Computer</a></td>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<td></td>
		<td><a href="#">Adam Versicherungen</a></td>
		<td>Bischweiler</td>
	</tr>
	<tr>
		<td></td>
		<td><a href="#">Adolph Versicherungen</a></td>
		<td>Karlsruhe</td>
	</tr>
	<tr>
		<td>
			<div>
				<img class="sponsor-img-small" alt="Katze" src="images/adler-apotheke.gif"/>
				<img class="sponsor-img-big" alt="Katze" src="images/adler-apotheke.gif"/>
			</div>
		</td>
		<td><a href="#">Adler Apotheke</a></td>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<td></td>
		<td><a href="#">Barmer, Krankenkasse</a></td>
		<td>Gaggenau</td>
	</tr>
</tbody>
</table>
<ul class="pagination">
  <li><a href="ueberuns-sponsoren.php">&laquo;</a></li>
  <li><a href="ueberuns-sponsoren.php">1</a></li>
  <li class="active"><a href="#">2</a></li>
  <li class="disabled"><a href="ueberuns-sponsoren3.php">3</a></li>
  <li class="disabled"><a href="ueberuns-sponsoren4.php">4</a></li>
  <li class="disabled" ><a href="ueberuns-sponsoren5.php">5</a></li>
  <li class="disabled"><a href="ueberuns-sponsoren3.php">&raquo;</a></li>
</ul>
	