	<div class="tabelle-2">
		<p>
			Hier finden Sie eine Liste all unserer aktiven Mitarbeiter. </br>Mit der Karte können Sie feststellen, wer von uns wo aktiv und ansprechbar ist.
		</p>
		<table id="tabelle-2" class="tablesorter">
			<thead>
				<tr>
					<th>Name</th>
					<th>Telefon</th>
					<th>Ort</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
				<tr>
					<td><a href="#">Pelle, Melony</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Buxtehude</td>
				</tr>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
				<tr>
					<td><a href="#">Bayer, Renate</a></td>
					<td>07225 / 919214</td>
					<td>Gernsbach-Scheuern</td>
				</tr>
			</tbody>
		</table>
	</div>

