<!--TODO: Muss später entfert werden-->
<!-- <link rel="stylesheet" type="text/css" href="../../css/tdh/tabelle-1.css"/>  -->
<table class="sponsoren-tab-1">
	<caption>
			<h3>Was wollen Sie sehen?</h3>
			<div>
				<label for="sponsorname">Firmenname:</label>
				<select id="sponsorname">
					<option value="" checked>---</option>
					<option value="A">A</option>
					<option value="B">B</option>
					<option value="C">C</option>
					<option value="D">D</option>
					<option value="E">E</option>
					<option value="F">F</option>
					<option value="G">G</option>
					<option value="H">H</option>
					<option value="I">I</option>
					<option value="J">J</option>
					<option value="K">K</option>
					<option value="L">L</option>
					<option value="M">M</option>
					<option value="N">N</option>
					<option value="O">O</option>
					<option value="P">P</option>
					<option value="Q">Q</option>
					<option value="R">R</option>
					<option value="S">S</option>
					<option value="T">T</option>
					<option value="U">U</option>
					<option value="V">V</option>
					<option value="W">W</option>
					<option value="X">X</option>
					<option value="Y">Y</option>
					<option value="Z">Z</option>
				</select>
				<label for="sponsorlocation">Ort:</label>
				<select id="sponsorlocation">
					<option value="" checked>---</option>
					<!--TODO: auslesen der orte und einfügen -->
					<option value="Bischweiler">Bischweiler</option>
					<option value="Gernsbach-Scheuern">Gernsbach-Scheuern</option>
					<option value="Karlsruhe">Karlsruhe</option>
					<option value="Kuppenheim">Kuppenheim</option>
					<option value="Gaggenau">Gaggenau</option>
				</select>
				
				<span>Auswahl treffen und dann</span>
				<a href="">&bull; Inhalt sotieren</a>
			</div>
		</caption>
	<tr>
		<th>
			<img src="images/einzelnachhilfe.gif"/>
			Abacus Nachhilfeinstitut
		</th>
		<td>Gernsbach-Scheuern</td>
	</tr>
	<tr>
		<th>ABAKUS Computer</th>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<th>Adam Versicherungen</th>
		<td>Bischweiler</td>
	</tr>
	<tr>
		<th>Adolph Versicherungen</th>
		<td>Karlsruhe</td>
	</tr>
	<tr>
		<th>
			<img src="images/adler-apotheke.gif"/>
			Adler Apotheke
		</th>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<th>Barmer, Krankenkasse</th>
		<td>Gaggenau</td>
	</tr>
	<!-- Kopie des erten Teils -->
	<tr>
		<th>
			<img src="images/einzelnachhilfe.gif"/>
			Abacus Nachhilfeinstitut 2
		</th>
		<td>Gernsbach-Scheuern</td>
	</tr>
	<tr>
		<th>ABAKUS Computer 2</th>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<th>Adam Versicherungen 2</th>
		<td>Bischweiler</td>
	</tr>
	<tr>
		<th>Adolph Versicherungen 2</th>
		<td>Karlsruhe</td>
	</tr>
	<tr>
		<th>
			<img src="images/adler-apotheke.gif"/>
			Adler Apotheke 2
		</th>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<th>Barmer, Krankenkasse 2</th>
		<td>Gaggenau</td>
	</tr>
</table>
	