<table name="sponsoren-tab-1" class="sponsoren-tab-1 responsive">
	<!--Tabellenkopf mit der Ansicht der Sortierung-->
	<caption>
		<h3>Sponsorenliste</h3>
		<form action="">
		  <div>
			<label for="alphabetic-list">Die Tabelle alphabetisch sortieren</label>
			<select id="alphabetic-list">
			  <option value="A">A</a></option>
			  <option value="B">B</a></option>
			  <option value="C">C</a></option>
			  <option value="D">D</a></option>
			  <option value="E">E</a></option>
			  <option value="F">F</a></option>
			  <option value="G">G</a></option>
			  <option value="H">H</a></option>
			  <option value="I">I</a></option>
			  <option value="J">J</a></option>
			  <option value="K">K</a></option>
			  <option value="L">L</a></option>
			  <option value="M">M</a></option>
			  <option value="N">N</a></option>
			  <option value="O">O</a></option>
			  <option value="P">P</a></option>
			  <option value="Q">Q</a></option>
			  <option value="R">R</a></option>
			  <option value="S">S</a></option>
			  <option value="T">T</a></option>
			  <option value="U">U</a></option>
			  <option value="V">V</a></option>
			  <option value="W">W</a></option>
			  <option value="X">X</a></option>
			  <option value="Y">Y</a></option>
			  <option value="Z">Z</a></option>
			</select>
			<span> nach </span>
			<input type="radio" name="alphabet" id="firmenname">
			<label for="firmenname">Firmenname</label>
			<input type="radio" name="alphabet" id="formenort">
			<label for="formenort">Ort</label>
			<input type="submit" value="sortieren lassen">
		  </div>
		</form>
	</caption>
	<thead>
		<tr>
			<th>Firmenlogo</th>
			<th>Name</th>
			<th>Ort</th>	
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<div class="tooltip" data-tooltip="http://beerhold.it/300/200" data-alttext="Ein total toller Alternativtext">
					<img class="sponsor-img-small" alt="Katze" src="http://beerhold.it/300/200"/>
				</div>
			</td>
			<td><a href="#">Abacus Nachhilfeinstitut</a></td>
			<td>Gernsbach-Scheuern</td>
		</tr>
		<tr>
			<td>
				<div class="sponsor-img">
					<img class="sponsor-img-small" alt="Katze" src="http://beerhold.it/301/200"/>
					<img class="sponsor-img-big" alt="Katze" src="http://beerhold.it/301/200"/>
				</div>
			</td>
			<td><a href="#">ABAKUS Computer</a></td>
			<td>Kuppenheim</td>
		</tr>
		<tr>
			<td>
				<div class="tooltip" data-tooltip="http://beerhold.it/302/200" data-alttext="Ein total toller Alternativtext">
					<img class="sponsor-img-small" alt="Katze" src="http://beerhold.it/302/200"/>
				</div>
			</td>
			<td><a href="#">Adam Versicherungen</a></td>
			<td>Bischweiler</td>
		</tr>
		<tr>
			<td>
				<div class="sponsor-img">
					<img class="sponsor-img-small" alt="Katze" src="http://beerhold.it/300/201"/>
					<img class="sponsor-img-big" alt="Katze" src="http://beerhold.it/300/201"/>
				</div>
			</td>
			<td><a href="#">Adolph Versicherungen</a></td>
			<td>Karlsruhe</td>
		</tr>
		<tr>
			<td>
				<div class="tooltip" data-tooltip="http://beerhold.it/301/202" data-alttext="Ein total toller Alternativtext">
					<img class="sponsor-img-small" alt="Katze" src="http://beerhold.it/301/202"/>
				</div>
			</td>
			<td><a href="#">Adler Apotheke</a></td>
			<td>Kuppenheim</td>
		</tr>
		<tr>
			<td>
				<div class="sponsor-img">
					<img class="sponsor-img-small" alt="Katze" src="http://beerhold.it/300/203"/>
					<img class="sponsor-img-big" alt="Katze" src="http://beerhold.it/300/203"/>
				</div>
			</td>
			<td><a href="#">Barmer, Krankenkasse</a></td>
			<td>Gaggenau</td>
		</tr>
	</tbody>
</table>
<!--Pagination unter der Tabelle-->
<div class="pagination">
	<ul>
		<li><a href="ueberuns-sponsoren2.php">&laquo;</a></li>
		<li><a href="ueberuns-sponsoren.php">1</a></li>
		<li><a href="ueberuns-sponsoren2.php">2</a></li>
		<li class="active"><a href="#">3</a></li>
		<li class="disabled"><a href="ueberuns-sponsoren4.php">4</a></li>
		<li class="disabled"><a href="ueberuns-sponsoren5.php">5</a></li>
		<li class="disabled"><a href="ueberuns-sponsoren4.php">&raquo;</a></li>
	</ul>
</div>
