<!--TODO: Muss später entfert werden-->
<link rel="stylesheet" type="text/css" href="../../css/tdh/tabelle-1.css"/> 
<table>
	<caption>
		<fieldset>
			<legend>Was wollen Sie sehen?</legend>
			<div>
				<!--TODO: selects-->
				<span>Auswahl treffen und dann</span>
				<a href="">&bull; Inhalt sotieren</a>
			</div>
		</fieldset>
	</caption>
	<tr>
		<th><!--TODO: bild einbauen-->
		Abacus Nachhilfeinstitut
		</th>
		<td>Gernsbach-Scheuern</td>
	</tr>
	<tr>
		<th>ABAKUS Computer</th>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<th>Adam Versicherungen</th>
		<td>Bischweiler</td>
	</tr>
	<tr>
		<th>Adolph Versicherungen</th>
		<td>Karlsruhe</td>
	</tr>
	<tr>
		<th><!--TODO: bild einbauen-->
		Adler Apotheke
		</th>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<th><!--TODO: bild einbauen-->
		Abacus Nachhilfeinstitut
		</th>
		<td>Gernsbach-Scheuern</td>
	</tr>
	<tr>
		<th>ABAKUS Computer</th>
		<td>Kuppenheim</td>
	</tr>
	<tr>
		<th>Adam Versicherungen</th>
		<td>Bischweiler</td>
	</tr>
	<tr>
		<th>Adolph Versicherungen</th>
		<td>Karlsruhe</td>
	</tr>
	<tr>
		<th><!--TODO: bild einbauen-->
		Adler Apotheke
		</th>
		<td>Kuppenheim</td>
	</tr>
</table>
	