
<div class="text-lb">
	<div class="ym-grid">
		<div class="ym-g33 ym-gl">
			<div class="text-lb-left">
				<!-- Pfad zum Bild am Ende noch korrigieren -->
				<img src="images/foerdergemeinschaft-logo.gif" alt="Logo der Fördergemeinschaft">
				<h2 class="text-lb-h2">Kindergärten &amp; Schulen</h2>
				<h3 class="text-lb-h3">Augusta Sybilla Schule</h3>
				<a href="www.schulwebseite.de">www.schulwebseite.de</a>
			</div>
		</div>
		<div class="ym-g66 ym-gr">
			<div class="text-lb-right">
				<a href="#close" class="text-lb-close-link">schließen</a>
				<h4 class="text-lb-h4">Wir danken für die Unterstützung als &lt;Kategorie&gt;</h4>
				
				<table>
					<caption>Meldungen</caption>
					<tr>
						<td>2009</td>
						<td>
							<ul>
								<li><a href="#">Auch die 19. Radbörse war ein Riesenerfolg - rund 2.000 Besucher</a></li>
								<li><a href="#">Auch die 19. Radbörse war ein Riesenerfolg - rund 2.000 Besucher</a></li>
							</ul>
						</td>
					</tr>
					<tr>
						<td>2008</td>
						<td>
							<ul>
								<li><a href="#">1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörs</a></li>
							</ul>
						</td>
					</tr>
					<tr>
						<td>2007</td>
						<td>
							<ul>
								<li><a href="#">Fahrradbörse brachte 2000 € Erlös</a></li>
							</ul>
						</td>
					</tr>
					<tr>
						<td>2006</td>
						<td>
							<ul>
								<li><a href="#">1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörs</a></li>
							</ul>
						</td>
					</tr>
					<tr>
						<td>2005</td>
						<td>
							<ul>
								<li><a href="#">Fahrradbörse brachte 2000 € Erlös</a></li>
							</ul>
						</td>
					</tr>
					<tr>
						<td>2004</td>
						<td>
							<ul>
								<li><a href="#">Fahrradbörse brachte 2000 € Erlös</a></li>
							</ul>
						</td>
					</tr>
					<tr>
						<td>2003</td>
						<td>
							<ul>
								<li><a href="#">1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörs</a></li>
							</ul>
						</td>
					</tr>
					<tr>
						<td>2002</td>
						<td>
							<ul>
								<li><a href="#">1600 Euro Erlös bei der 18. Kuppenheimer Fahrradbörs</a></li>
							</ul>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>