<div class="ym-grid zusatzwidget-content">
  <h2>Unsere Spendenkonten</h2>
  <div class="ym-g50 ym-gl">
    
    <div class="ym-gbox-left"><img src="#" alt="">
    <h3>Sparkasse</h3>
      Baden-Baden/ Gaggenau
      <table class="zusatzwidget-content-6">
        <tr>
          <th>Konto-Nr.</th>
          <td>120 790</td> </tr>
        <tr>
          <th>BLZ</th>
          <td>662 500 30</td> </tr>
      </table>
      
       </div>
  </div>
  <div class="ym-g50 ym-gr">
    <div class="ym-gbox-right">
        <h3>Volksbank</h3>
      Osnabrück
      <table class="zusatzwidget-content-6">
        <tr>
          <th>Konto-Nr.</th>
          <td>700 800 700</td> </tr>
        <tr>
          <th>BLZ</th>
          <td>265 900 25</td> </tr>
      </table>
    </div> 
  </div>
</div>