<div class="ym-grid zusatzwidget-content-6">
  <h2>Unsere Spendenkonten</h2>
  <div class="ym-g50 ym-gl">
    
    <div class="ym-gbox-left"><img src="#" alt="">
    <h3>Sparkasse</h3>
		<caption style="caption-side:bottom">Baden-Baden/ Gaggenau</caption>
	<table>
        <tr>
          <th>Konto-Nr.</th>
          <td>120 790</td> </tr>
        <tr>
          <th>BLZ</th>
          <td>662 500 30</td> </tr>
      </table>
      
       </div>
  </div>
  <div class="ym-g50 ym-gr">
    <div class="ym-gbox-right">
        <h3>Volksbank</h3>
      <caption style="caption-side:bottom">Osnabr&uuml;ck</caption>
      <table>
        <tr>
          <th>Konto-Nr.</th>
          <td>700 800 700</td> </tr>
        <tr>
          <th>BLZ</th>
          <td>265 900 25</td> </tr>
      </table>
    </div> 
  </div>
</div>