
<div class="ym-grid zusatzwidget-content">
  <h2>Das Team</h2>
  <div class="ym-g40 ym-gl">
    
    
    <div class="ym-gbox-left"><img src="#" alt=""></div>
  </div>
  <div class="ym-g60 ym-gr">
    <div class="ym-gbox-right"></div>
    <p>Schreiben Sie uns eine 
    <a class="zusatzwidget-content-5" href="#">Email</a>
    oder rufen Sie einen
    <a class="zusatzwidget-content-5" href="#">Mitarbeiter</a>
    an, wir informieren Sie gerne persönlich.</p>
    <a class="zusatzwidget-content-5" href="#">
      Hier finden Sie eine Liste all unsere aktiven Mitarbeiter.
    </a>
  </div>
</div>