<div class="ym-grid zusatzwidget-content">
  <div class="ym-gl">
    <h2>Die Macher</h2>
    <div class="ym-gbox-left"><img src="#" alt=""></div>
	<ul class="zusatzwidget-content-4">
		<li class="zusatzwidget-content-4">Macher Vorname Nachname 1</li>
		<li class="zusatzwidget-content-4">Macher Vorname Nachname 2</li>
		<li class="zusatzwidget-content-4">Macher Vorname Nachname 3</li>
	</ul>
	<a class="zusatzwidget-content-5" href="#">Alle Macher</a>
  </div>
</div>