<div class="ym-grid zusatzwidget-content-6">
  <h3>Unsere Spendenkonten</h3>
  <div class="ym-g50 ym-gl">
    
    <div class="ym-gbox-left left-content-6">
    <h4>Sparkasse</h4>
		<caption >Baden-Baden/ Gaggenau</caption>
	<table>
        <tr>
          <th>Konto-Nr.</th>
          <td>120 790</td> </tr>
        <tr>
          <th>BLZ</th>
          <td>662 500 30</td> </tr>
      </table>
      
       </div>
  </div>
  <div class="ym-g50 ym-gr">
    <div class="ym-gbox-right right-content-6">
        <h4>Volksbank</h4>
      <caption>Osnabr&uuml;ck</caption>
      <table>
        <tr>
          <th>Konto-Nr.</th>
          <td>700 800 700</td> </tr>
        <tr>
          <th>BLZ</th>
          <td>265 900 25</td> </tr>
      </table>
    </div> 
  </div>
</div>