
<div class="ym-grid zusatzwidget-content-5">
  <h2>Das Team</h2>
  <div class="ym-g40 ym-gl">
    <div class="ym-gbox-left">
		<img src="images/team-beispielbild.jpg"  alt="Team Bild" >
	</div>
  </div>
  <div class="ym-g60 ym-gr">
    <div class="ym-gbox-right"></div>
    <p>Schreiben Sie uns eine 
		<a  href="#">Email</a>
		oder rufen Sie einen
		<a  href="#">Mitarbeiter</a>
		an, wir informieren Sie gerne pers&ouml;nlich.
	</p>
    <a  href="#">
      Hier finden Sie eine Liste all unsere aktiven Mitarbeiter.
    </a>
  </div>
</div>