
<div class="ym-grid zusatzwidget-content-5">
  <h3>Das Team</h3>
  <div class="ym-g40 ym-gl left-content-5">
    <div class="ym-gbox-left">
		<img class="flexible" src="images/team-beispielbild.jpg"  alt="Team Bild" >
	</div>
  </div>
  <div class="ym-g60 ym-gr right-content-5">
    <div class="ym-gbox-right"></div>
    <p>Schreiben Sie uns eine 
		<a  href="#">Email</a>
		oder rufen Sie einen
		<a  href="#">Mitarbeiter</a>
		an, wir informieren Sie gerne persönlich.
	</p>
    <a  href="#">
      Hier finden Sie eine Liste all unsere aktiven Mitarbeiter.
    </a>
  </div>
</div>
