<div class="ym-grid zusatzwidget-content-6">
  <h2>Erdbeben in Haiti</h2>
  <div class="ym-g50 ym-gl g50-content-6">
    
    <div class="ym-gbox-left left-content-6">
        <p>Hier finden Sie alle wichtigen Meldungen zu dem verheerenden Erdbeben in Haiti Bitte unterstützen Sie uns weiterhin mit Spenden. Ihre Spende - Stichwort: "Erdbeben Haiti". Alle Spenden reichen wir weiter an die Partnerorganisation tdh Lausanne, die vor Ort Hilfe leistet.</p>
   </div>
  </div>
  <div class="ym-g50 ym-gr  g50-content-6">
    <div class="ym-gbox-right right-content-6">
        <ul>
            <li><strong>Spendenkonto</strong>	120 790</li>
            <li>Sparkasse Baden-Baden / Gaggenau</li>
            <li>BLZ 662 500 30</li>
        </ul>
        <ul>
            <li><strong>Spendenkonto</strong>	102 748 00</li>
            <li>VoBa Baden-Baden / Rastatt</li>
            <li>BLZ 662 900 00</li>
        </ul>
    </div> 
  </div>
</div>