            </div>
            <!-- /.ym-column -->
            <footer>
                <span class="float-left">&copy; 2014 terre des hommes Mittelbaden/Murgtal</span> <a class="float-right" href="impressum.php">Impressum</a>
            </footer>
        </div>
        <!-- /.ym-wbox -->
    </div>
    <!-- /.ym-wrapper -->
    <script src="js/jquery.js" type="text/javascript"></script>
    <script src="js/tdh.js" type="text/javascript"></script>
    
</body>
</html>